### PR TITLE
Terminal user interface

### PR DESCRIPTION
**Pull request by chrusty**
Initial version of a terminal UI. Either runs as a stand-alone remote-control UI (the `ui` command), or as a UI for whatever you want to play (`load` and `playlist` commands when `--with-ui`).

Features
---------
* Uses gocui (a simple GUI manager based on termbox)
* Play/Pause
* Seek forwards/backwards 
* Displays current position
* Logs go to their own "window"
* Volume-up / volume-down
* Volume muting
* Integrates with the `load` and `playlist` commands (if you use the `--with-ui` flag)

Still to do (in a future PR)
-------------------------
* Include a playlist view (to show what has played, is playing, and what is coming up)
* Include a file-browser (to select new stuff to play)

Changes
---------
**`UI` package**:
* Terminal UI
* Views for status, volume, progress, log, and key-help

**`CMD` package**:
* Added `ui` command (runs go-chromecast with a UI, to control whatever is already playing on the chromecast)
* Added the `--with-ui` flag (makes the `load` and `playlist` commands run with a UI)

**`Application` package**:
* Custom error types
* SetVolume() method
* SetMuted() method
* Structured logging with logrus

**`Cast` package**:
* Structured logging with logrus
* Unique message for SetVolume
* Attempt at MediaMetadata

go-chromecast-ui

### CODE REVIEW

**Comment by chrusty** [comment]
screen shot 2018-12-31 at 17 00 18

**Comment by vishen** [comment]
This is awesome work! I have no strong opinion on whether it should open in the same or a separate terminal, so happy with whatever you reckon.

**Comment by chrusty** [comment]
@vishen OK man I've got it working with the `load` and `playlist` commands, added a bunch of stuff, generally tidied it up a bit.

If you're up for it then merge this in and I'll get the other features coming in another PR (this one is already massive).

**Comment by vishen** [comment]
@chrusty Awesome, nice work man! This looks fine to me, I'll merge this.

**Pull request merged**
