### PR TITLE
Add cli argument parsing for transcode command

### PR DESCRIPTION
**Pull request by Galiley**

### CODE REVIEW

**Review by vishen — COMMENTED** [review]
What is the issue this is trying to solve? I haven't used the `transcode` function in a while, so my memory is a bit fuzzy; but doesn't it already take a command with command line arguments?

**Comment by Galiley** [comment]
Because of how `os.Exec` works in Goland where it is necessary to provide the command and the args separately, in the transcode command, the command flag was split with space as a separator which caused an issue if you have space in one of the transcode command args.
This PR adds the possibility to use the parsed cli args with cobra for the transcode command while keeping backward compatibility when using the command flags

**Comment by vishen** [comment]
>  the command flag was split with space as a separator which caused an issue if you have space in one of the transcode command args

This makes sense.

Thanks for the PR!

**Comment by Disonantemus** [comment]
- I can't find a way to use **transcode** command without error.
- Please post an example here , in the _README_ or else.
- I did ask 4 it at [Issue #163 ](https://github.com/vishen/go-chromecast/issues/163), but didn't get any example.
- This would be very helpful, thanks.

**Pull request merged**
